# Generated by Django 3.0.6 on 2020-05-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiLoginUserData2',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.TextField(blank=True, null=True)),
                ('mark_attandance', models.BooleanField(default=True)),
            ],
        ),
    ]
